name: aqk build system 

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE:
        description: "Put the Model of your phone, remember it starts with SM-"
        required: true
        default: "SM-A325F"
      USE_UI_8_TETHERING_APEX:
        description: "Set True if your kernel BPF version is lower than 5.10"
        required: true
        default: "False"

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
  
    - name: Cleaning junk files
      uses: rokibhasansagar/slimhub_actions@v25.42.5

    - name: Install required packages
      run: |
        sudo apt install -y \
          p7zip-full lz4 android-sdk-libsparse-utils \
          python3 python3-pip zipalign unzip default-jre openjdk-17-jdk brotli e2fsprogs
        pip3 install liblp tgcrypto pyrogram gdown

        chmod +x bin/erofs-utils/extract.erofs
        chmod +x bin/erofs-utils/mkfs.erofs

    - name: Setup directories
      run: |
        chmod +x scripts/setup_directories.sh
        chmod +x scripts/zip_creation.sh
        chmod +x scripts/Knox_script.sh
        bash scripts/setup_directories.sh FIRMWARE WORK OUT
    
    - name: Set build environment
      shell: bash
      run: |
        echo "STOCK_DEVICE=${{ github.event.inputs.STOCK_DEVICE }}" >> $GITHUB_ENV
        echo "USE_UI_8_TETHERING_APEX=${{ github.event.inputs.USE_UI_8_TETHERING_APEX }}" >> $GITHUB_ENV
        echo "OUTPUT_FILESYSTEM=erofs" >> $GITHUB_ENV
        echo "AQK_VERSION=1.0.1" >> $GITHUB_ENV

        echo "OUT_DIR=$PWD/OUT" >> $GITHUB_ENV
        echo "WORK_DIR=$PWD/WORK" >> $GITHUB_ENV
        echo "FIRM_DIR=$PWD/FIRMWARE" >> $GITHUB_ENV
        echo "DEVICES_DIR=$PWD/aqk-stuff/Devices" >> $GITHUB_ENV
        echo "APKTOOL=$PWD/bin/apktool/apktool.jar" >> $GITHUB_ENV
        echo "VNDKS_COLLECTION=$PWD/aqk-stuff/vndks" >> $GITHUB_ENV
        echo "BUILD_PARTITIONS=product,vendor,odm,system_ext,system" >> $GITHUB_ENV

    - name: Check repo
      shell: bash
      env:
        LUMIROM_BUILD: ${{ secrets.LUMIROM_BUILD }}
        OFFICIAL_HASH: ${{ secrets.OFFICIAL_HASH }}
      run: |
        source scripts/aqk-main.sh
        IS_OFFICIAL

    - name: Download firmware
      shell: bash
      env:
        DOWNLOAD_LINK: ${{ secrets.DOWNLOAD_LINK }}
        LINK_HASH: ${{ secrets.LINK_HASH }}
      run: |
        source scripts/aqk-main.sh
        source "$DEVICES_DIR/$STOCK_DEVICE/config"
        DOWNLOAD_FIRMWARE "$TARGET_DEVICE" "$FIRM_DIR"

    - name: Extract firmware
      shell: bash
      run: |
        source scripts/aqk-main.sh
        EXTRACT_FIRMWARE "$FIRM_DIR/$TARGET_DEVICE"
        PREPARE_PARTITIONS "$FIRM_DIR/$TARGET_DEVICE"
        EXTRACT_FIRMWARE_IMG "$FIRM_DIR/$TARGET_DEVICE"

    - name: Apply vendor patches
      shell: bash
      run: |
        source scripts/aqk-main.sh
        DISABLE_FBE "$FIRM_DIR/$TARGET_DEVICE"
        DISABLE_FDE "$FIRM_DIR/$TARGET_DEVICE"
        DELETE_ICCC "$FIRM_DIR/$TARGET_DEVICE"
        DEBLOAT_VENDOR "$FIRM_DIR/$TARGET_DEVICE"
        PATCH_FSTAB_EROFS "$FIRM_DIR/$TARGET_DEVICE"

    - name: Apply stock config
      shell: bash
      run: |
        source scripts/aqk-main.sh
        APPLY_STOCK_CONFIG "$FIRM_DIR/$TARGET_DEVICE"

    - name: Debloat ROM
      shell: bash
      run: |
        source scripts/aqk-main.sh
        DEBLOAT "$FIRM_DIR/$TARGET_DEVICE"

    - name: Apply features
      shell: bash
      run: |
        source scripts/aqk-main.sh
        APPLY_FEATURES "$FIRM_DIR/$TARGET_DEVICE"

    - name: Update Build ID
      shell: bash
      run: |
        source scripts/aqk-main.sh
        APPENDING_DISPLAY_ID "$FIRM_DIR/$TARGET_DEVICE"

    - name: Install stock framework-res
      shell: bash
      run: |
        source scripts/aqk-main.sh
        INSTALL_FRAMEWORK \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/framework-res.apk"

    - name: Decompile framework jars
      shell: bash
      run: |
        source scripts/aqk-main.sh
        DECOMPILE "$APKTOOL" \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/ssrm.jar" "$WORK_DIR"
        DECOMPILE "$APKTOOL" \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/services.jar" "$WORK_DIR"

    - name: Patch Knox
      shell: bash
      run: |
        source scripts/aqk-main.sh
        PATCH_SSRM "$WORK_DIR/ssrm"
        PATCH_KNOX_GUARD "$WORK_DIR/services"
        PATCH_FLAG_SECURE "$WORK_DIR/services"
        PATCH_SECURE_FOLDER "$WORK_DIR/services"
        PATCH_PRIVATE_SHARE "$WORK_DIR/services"
        DISABLE_SIGNATURE_VERIFICATION "$WORK_DIR/services"

    - name: Recompile framework
      shell: bash
      run: |
        source scripts/aqk-main.sh
        RECOMPILE "$APKTOOL" "$WORK_DIR/ssrm" \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework" "$WORK_DIR"
        RECOMPILE "$APKTOOL" "$WORK_DIR/services" \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework" "$WORK_DIR"
        cp -fv "$WORK_DIR"/*.jar \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/"

    - name: Build ROM
      shell: bash
      run: |
        source scripts/aqk-main.sh
        BUILD_IMG "$FIRM_DIR/$TARGET_DEVICE" "$OUTPUT_FILESYSTEM" "$OUT_DIR"
        IMG_TO_BROTLI "$OUT_DIR" "TMP"

    - name: Update updater-script
      shell: bash
      run: |
        source scripts/zip_creation.sh
        UPDATE_ZIP_SCRIPT "$FIRM_DIR/$TARGET_DEVICE"
        
    - name: Prepare flashable zip
      shell: bash
      run: |
        source scripts/zip_creation.sh
        FLASHABLE_ZIP_CREATION

    - name: Sending ROM to GoFile.
      run: |
          chmod +x ./upload.sh 
          bash ./upload.sh "$(pwd)/template/${ZIP_NAME}"

    - name: Cleanup
      run: |
        sudo rm -rf *
